# Generated by Django 5.2.7 on 2025-10-26 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0002_assignee_reviewer_remove_task_assignee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='assignee',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assignee_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='reviewer_id',
        ),
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks_app.assignee'),
        ),
        migrations.AddField(
            model_name='task',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks_app.reviewer'),
        ),
        migrations.AlterField(
            model_name='assignee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='reviewer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(),
        ),
    ]
