# Generated by Django 5.2.7 on 2025-10-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0004_alter_task_assignee_alter_task_reviewer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
