# Generated by Django 5.2.7 on 2025-10-31 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0006_taskmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCommentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='TaskModel',
        ),
    ]
