# Generated by Django 5.2.7 on 2025-10-31 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0007_taskcommentsmodel_delete_taskmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcommentsmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='taskcommentsmodel',
            name='created_at',
        ),
    ]
