# Generated by Django 5.2.7 on 2025-11-07 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0010_backfill_board_owners'),
        ('tasks_app', '0009_taskcommentsmodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='board_app.board'),
        ),
        migrations.AlterField(
            model_name='task',
            name='comments_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
