# Generated by Django 5.2.7 on 2025-11-07 20:06

from django.db import migrations

def fix_null_author(apps, schema_editor):
    TaskCommentsModel = apps.get_model('tasks_app', 'TaskCommentsModel')
    User = apps.get_model('auth', 'User')
    # Pick a fallback user (e.g., first superuser or first user)
    fallback_user = User.objects.filter(is_superuser=True).first() or User.objects.order_by('id').first()
    if fallback_user:
        TaskCommentsModel.objects.filter(author__isnull=True).update(author=fallback_user)


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0010_alter_task_board_alter_task_comments_count'),
    ]

    operations = [
        migrations.RunPython(fix_null_author, migrations.RunPython.noop),
    ]
