# Generated by Django 5.2.7 on 2025-10-14 19:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boardmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('member_count', models.PositiveIntegerField()),
                ('ticket_count', models.PositiveIntegerField()),
                ('tasks_to_do_count', models.PositiveBigIntegerField()),
                ('tasks_high_prio_count', models.PositiveBigIntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_board', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
