# Generated by Django 5.2.7 on 2025-10-19 17:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0002_rename_boardmodel_board'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='members',
            field=models.ManyToManyField(related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='board',
            name='tasks_high_prio_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='tasks_to_do_count',
            field=models.PositiveIntegerField(),
        ),
    ]
