# Generated by Django 5.2.7 on 2025-10-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_board_members_alter_board_tasks_high_prio_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='member_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='tasks_high_prio_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='tasks_to_do_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='board',
            name='ticket_count',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
