# Generated by Django 5.2.7 on 2025-10-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0004_alter_board_member_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.AlterField(
            model_name='board',
            name='member_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='tasks_high_prio_count',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='tasks_to_do_count',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='board',
            name='ticket_count',
            field=models.PositiveIntegerField(),
        ),
    ]
