# Generated by Django 5.2.6 on 2025-10-23 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0006_board_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='member_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='members',
        ),
        migrations.RemoveField(
            model_name='board',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks_high_prio_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tasks_to_do_count',
        ),
        migrations.RemoveField(
            model_name='board',
            name='ticket_count',
        ),
    ]
