# Generated by Django 5.2.7 on 2025-11-04 09:47

from django.db import migrations

def backfill_board_owners(apps, schema_editor):
    Board = apps.get_model('board_app', 'Board')
    User = apps.get_model('auth', 'User')

    # Check if any users exist (skip if database is empty, e.g., for new clones)
    if not User.objects.exists():
        return # No users, no backfill needed
    
    # Find a suitable owner: prefer superuser, then first user by ID
    owner = User.objects.filter(is_superuser=True).first()
    if not owner:
        owner = User.objects.order_by('id').first()
    if not owner:
        return # Fallback: no suitable owner found, skip
    
    # Find boards with NULL owner
    qs = Board.objects.filter(owner__isnull=True)
    board_ids = list(qs.values_list('id', flat=True))

    # Fast bulk update
    qs.update(owner=owner)

    # Optional: ensure the owner is also a member of those boards
    if board_ids:
        for b in Board.objects.filter(id__in=board_ids).iterator():
            b.members.add(b.owner)

class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0009_singleboard_board_owner'),
    ]

    operations = [
        migrations.RunPython(backfill_board_owners, migrations.RunPython.noop),
    ]