# Generated by Django 5.2.7 on 2025-11-04 09:47

from django.db import migrations

def backfill_board_owners(apps, schema_editor):
    Board = apps.get_model('board_app', 'Board')
    User = apps.get_model('auth', 'User')

    try:
        owner = User.objects.get(username='Claude Mitchell')
    except User.DoesNotExist:
        raise ValueError("Target owner user not found. Adjust the lookup in the migration.")
    
    # owner = User.objects.filter(is_superuser=True).first() or User.objects.order_by('id').first()
    # if not owner:
    #     return
    
    # Find boards with NULL owner
    qs = Board.objects.filter(owner__isnull=True)
    board_ids = list(qs.values_list('id', flat=True))

    # Fast bulk update
    qs.update(owner=owner)

    # Optional: ensure the owner is also a member of those boards
    if board_ids:
        for b in Board.objects.filter(id__in=board_ids).iterator():
            b.members.add(b.owner)

class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0009_singleboard_board_owner'),
    ]

    operations = [
        migrations.RunPython(backfill_board_owners, migrations.RunPython.noop),
    ]