# Generated by Django 5.2.7 on 2025-11-17 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0010_backfill_board_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='singleboard',
            name='members',
            field=models.ManyToManyField(related_name='single_boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='singleboard',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='single_owner_boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
