# Generated by Django 5.2.7 on 2025-11-17 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0011_singleboard_members_singleboard_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SingleBoard',
        ),
    ]
